export type RootStackParamList = {
  WelcomeScreen: undefined;
  MarketScreen: {comment: string; rating: number};
  FindScreen: undefined;
  BusinessEntryScreen: undefined;
  CustomerEntryScreen: undefined;
  NonBusinessEntryScreen: undefined;
  RegisterScreen: undefined;
  VerificationScreen: undefined;
  FavsScreen: undefined;
  ProfileScreen: undefined;
  SettingsScreen: undefined;
  CampaignScreen: undefined;
  HomeScreen: undefined;
  CategoriesScreen: {storeId: string};
  CommentScreen: undefined;
  BEntryScreen: undefined;
  BRegisterScreen: undefined;
  ContiuneRegisterScreen: undefined;
  BVerificiationScreen: undefined;
  PriceEntryScreen: undefined;
  BussinesHomeScreen: undefined;
  BussinesProfileScreen: undefined;
  AddresUpdateScreen: undefined;
  PastProjectsUpdateScreen: undefined;
  PriceUpdateScreen: undefined;
  BussinesSettingsScreen: undefined;
  EditCampaignScreen: undefined;
  AddCampaignScreen: undefined;
  BussinesCampaignScreen: undefined;
  NonBussinesRegisterScreen: undefined;
  NBVerificiationScreen: undefined;
  ContiuneNonRegisterScreen: undefined;
  NonPriceEntryScreen: undefined;
  NonBusinessHomeScreen: undefined;
  NonBussinesProfileScreen: undefined;
  NonBussinesCampaignScreen: undefined;
  MeetingScreen: {
    ownerId: string;
    selectedServices: {
      operationName: string;
      quantity: number;
      id: string;
      price: number;
    }[];
    profileData: any;
  };
  Try: undefined;
};
